# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Uncomment the following line to enable the Sofle OLED Display
# CONFIG_ZMK_DISPLAY=y

# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment this line below to add rgb underglow / backlight support
# CONFIG_ZMK_RGB_UNDERGLOW=y

# Uncomment the line below to disable external power toggling by the underglow.
# By default toggling the underglow on and off also toggles external power
# on and off. This also causes the display to turn off.
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Keyboard name configuration
CONFIG_ZMK_KEYBOARD_NAME="MangaTholi"

# Battery reporting and split BLE central configuration
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Fixes the Windows Bluetooth battery reporting bug
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Mouse support configuration
CONFIG_ZMK_MOUSE=y

# Enable ZMK Studio - use along with snippet: studio-rpc-usb-uart in build.yaml file.
CONFIG_ZMK_STUDIO=y
# Disable studio locking
CONFIG_ZMK_STUDIO_LOCKING=n